# Generated by Django 4.1.3 on 2022-12-01 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comment_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='date_created',
            new_name='dateCreated',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date_created',
        ),
    ]
